sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t project3cht/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true project3cht/docker-react npm run test
